python3 run.py \
--data_path ETTh1.csv \
--model_id ETTh1_96_96 \
--model Crossformer \
--data custom \
--features M \
--seq_len 96 \
--label_len 24 \
--pred_len 96 \
--e_layers 2 \
--d_layers 1 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--freq h \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path ETTh1.csv \
--model_id ETTh1_96_192 \
--model Crossformer \
--data custom \
--features M \
--seq_len 96 \
--label_len 24 \
--pred_len 192 \
--e_layers 2 \
--d_layers 1 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--freq h \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path ETTh1.csv \
--model_id ETTh1_96_336 \
--model Crossformer \
--data custom \
--features M \
--seq_len 96 \
--label_len 24 \
--pred_len 336 \
--e_layers 2 \
--d_layers 1 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--freq h \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path ETTh1.csv \
--model_id ETTh1_96_720 \
--model Crossformer \
--data custom \
--features M \
--seq_len 96 \
--label_len 24 \
--pred_len 720 \
--e_layers 2 \
--d_layers 1 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--freq h \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path ETTh1.csv \
--model_id ETTh1_192_96 \
--model Crossformer \
--data custom \
--features M \
--seq_len 192 \
--label_len 24 \
--pred_len 96 \
--e_layers 2 \
--d_layers 1 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--freq h \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path ETTh1.csv \
--model_id ETTh1_192_192 \
--model Crossformer \
--data custom \
--features M \
--seq_len 192 \
--label_len 24 \
--pred_len 192 \
--e_layers 2 \
--d_layers 1 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--freq h \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path ETTh1.csv \
--model_id ETTh1_192_336 \
--model Crossformer \
--data custom \
--features M \
--seq_len 192 \
--label_len 24 \
--pred_len 336 \
--e_layers 2 \
--d_layers 1 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--freq h \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path ETTh1.csv \
--model_id ETTh1_192_720 \
--model Crossformer \
--data custom \
--features M \
--seq_len 192 \
--label_len 24 \
--pred_len 720 \
--e_layers 2 \
--d_layers 1 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--freq h \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path ETTh1.csv \
--model_id ETTh1_336_96 \
--model Crossformer \
--data custom \
--features M \
--seq_len 336 \
--label_len 24 \
--pred_len 96 \
--e_layers 2 \
--d_layers 1 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--freq h \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path ETTh1.csv \
--model_id ETTh1_336_192 \
--model Crossformer \
--data custom \
--features M \
--seq_len 336 \
--label_len 24 \
--pred_len 192 \
--e_layers 2 \
--d_layers 1 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--freq h \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path ETTh1.csv \
--model_id ETTh1_336_336 \
--model Crossformer \
--data custom \
--features M \
--seq_len 336 \
--label_len 24 \
--pred_len 336 \
--e_layers 2 \
--d_layers 1 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--freq h \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path ETTh1.csv \
--model_id ETTh1_336_720 \
--model Crossformer \
--data custom \
--features M \
--seq_len 336 \
--label_len 24 \
--pred_len 720 \
--e_layers 2 \
--d_layers 1 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--freq h \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

