python3 run.py \
--data_path weather.csv \
--model_id weather_96_96 \
--model iTransformer \
--data custom \
--features M \
--seq_len 96 \
--label_len 24 \
--pred_len 96 \
--e_layers 2 \
--d_layers 1 \
--enc_in 21 \
--dec_in 21 \
--c_out 21 \
--freq t \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path weather.csv \
--model_id weather_96_192 \
--model iTransformer \
--data custom \
--features M \
--seq_len 96 \
--label_len 24 \
--pred_len 192 \
--e_layers 2 \
--d_layers 1 \
--enc_in 21 \
--dec_in 21 \
--c_out 21 \
--freq t \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path weather.csv \
--model_id weather_96_336 \
--model iTransformer \
--data custom \
--features M \
--seq_len 96 \
--label_len 24 \
--pred_len 336 \
--e_layers 2 \
--d_layers 1 \
--enc_in 21 \
--dec_in 21 \
--c_out 21 \
--freq t \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path weather.csv \
--model_id weather_96_720 \
--model iTransformer \
--data custom \
--features M \
--seq_len 96 \
--label_len 24 \
--pred_len 720 \
--e_layers 2 \
--d_layers 1 \
--enc_in 21 \
--dec_in 21 \
--c_out 21 \
--freq t \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path weather.csv \
--model_id weather_192_96 \
--model iTransformer \
--data custom \
--features M \
--seq_len 192 \
--label_len 24 \
--pred_len 96 \
--e_layers 2 \
--d_layers 1 \
--enc_in 21 \
--dec_in 21 \
--c_out 21 \
--freq t \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path weather.csv \
--model_id weather_192_192 \
--model iTransformer \
--data custom \
--features M \
--seq_len 192 \
--label_len 24 \
--pred_len 192 \
--e_layers 2 \
--d_layers 1 \
--enc_in 21 \
--dec_in 21 \
--c_out 21 \
--freq t \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path weather.csv \
--model_id weather_192_336 \
--model iTransformer \
--data custom \
--features M \
--seq_len 192 \
--label_len 24 \
--pred_len 336 \
--e_layers 2 \
--d_layers 1 \
--enc_in 21 \
--dec_in 21 \
--c_out 21 \
--freq t \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path weather.csv \
--model_id weather_192_720 \
--model iTransformer \
--data custom \
--features M \
--seq_len 192 \
--label_len 24 \
--pred_len 720 \
--e_layers 2 \
--d_layers 1 \
--enc_in 21 \
--dec_in 21 \
--c_out 21 \
--freq t \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path weather.csv \
--model_id weather_336_96 \
--model iTransformer \
--data custom \
--features M \
--seq_len 336 \
--label_len 24 \
--pred_len 96 \
--e_layers 2 \
--d_layers 1 \
--enc_in 21 \
--dec_in 21 \
--c_out 21 \
--freq t \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path weather.csv \
--model_id weather_336_192 \
--model iTransformer \
--data custom \
--features M \
--seq_len 336 \
--label_len 24 \
--pred_len 192 \
--e_layers 2 \
--d_layers 1 \
--enc_in 21 \
--dec_in 21 \
--c_out 21 \
--freq t \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path weather.csv \
--model_id weather_336_336 \
--model iTransformer \
--data custom \
--features M \
--seq_len 336 \
--label_len 24 \
--pred_len 336 \
--e_layers 2 \
--d_layers 1 \
--enc_in 21 \
--dec_in 21 \
--c_out 21 \
--freq t \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

python3 run.py \
--data_path weather.csv \
--model_id weather_336_720 \
--model iTransformer \
--data custom \
--features M \
--seq_len 336 \
--label_len 24 \
--pred_len 720 \
--e_layers 2 \
--d_layers 1 \
--enc_in 21 \
--dec_in 21 \
--c_out 21 \
--freq t \
--des Exp \
--itr 1 \
--train_epochs 10 \
--batch_size 256 \

